public class Soal {
    // {"nomer e", "soal e", "jawaban sing bener", "jawaban A", "jawaban B",
    // "jawaban C", "jawaban D"}
    Object[][] array = {
            { 1, "Binatang apa yang bisa hidup di darat dan air?", "Amfibi", "Carnivora", "Mamalia", "Amfibi",
                    "Herbivora" },
            { 2, "Negara terluas keempat di dunia adalah ?", "Amerika", "Rusia", "India", "Amerika", "Canada" },
            { 3, "Monumen terkenal di Paris adalah ?", "Menara Eiffel", "Menara Eiffel", "Piramida", "Borobudur",
                    "Menara Pisa" },
            { 4, "Bahan bakar kereta api adalah ?", "Batubara", "Avtur", "Batubara", "Bensin", "Solar" },
            { 5, "Gunung tertinggi di dunia adalah ?", "Gunung Everest", "Gunung K2", "Gunung Makalu", "Gunung Lhotse",
                    "Gunung Everest" },
            { 6, "Angkor Wat terdapat di negara ?", "Kamboja", "Kamboja", "Thailand", "Vietnam", "India" },
            { 7, "Serangga yang mempunyai solidaritas tinggi ?", "Semut", "Lebah", "Semut", "Capung", "Lalat" },
            { 8, "Seni menulis arab disebut ?", "Kaligrafi", "Kaligrafi", "Grafitti", "Mural", "Vandal" },
            { 9, "Mamalia tertinggi adalah ?", "Jerapah", "Gajah", "Kuda Nil", "Jerapah", "Unta" },
            { 10, "Novel Harry Potter terbit pada tahun ?", "1997", "1996", "1997", "1998", "1999" },
            { 11, "Benua terluas di permukaan bumi adalah", "Asia", "Amerika", "Afrika", "Asia", "Australia" },
            { 12, "Secara astronomis, Benua Eropa terletak pada 9°BB-60°BT dan 35°LU-80°LU. Berdasarkan letak tersebut, maka Benua Eropa memiliki iklim",
                    "subtropis dan sedang", "sedang dan dingin", "tropis dan subtropis", "subtropis dan sedang",
                    "subtropis dan dingin" },
            { 13, "Gubernur provinsi Jawa Timur yang pertama adalah", "R.T. Soeryo", "Dr. Moedjani", "R. Samadikun",
                    "R.T. Soeryo", "Imam Utomo" },
            { 14, "Thailand, Indonesia, dan Vietnam merupakan negara produsen karet terbesar di dunia. Getah karet bermanfaat bagi kehidupan manusia, yaitu",
                    "sebagai bahan baku pembuatan ban", "sebagai bahan baku mebel", "sebagai bahan baku makanan ringan",
                    "sebagai bahan baku pembuatan ban", "berfungsi menyerap karbondioksida di udara" },
            { 15, "Negara Jepang merupakan salah satu negara kepulauan yang ada di dunia. Negara ini memiliki sumber daya perikanan yang sangat tinggi. Faktor yang menyebabkan hal tersebut terjadi adalah",
                    "berada di zona pertemuan dua arus yang berbeda", "memiliki banyak gunung api",
                    "memiliki perairan laut dangkal", "berada di zona pertemuan lempeng",
                    "berada di zona pertemuan dua arus yang berbeda" },
            { 16, "Sebagian besar penduduk yang berasal dari wilayah Asia Timur dan Asia Tenggara adalah ras",
                    "Mongoloid", "Negroid", "Kaukasoid", "Mongoloid", "Europoid" },
            { 17, "Tiongkok merupakan negara dengan jumlah penduduk terbanyak di dunia. Pada tahun 2017, jumlah penduduk Tiongkok mencapai 1,386 miliar jiwa. Langkah yang dilakukan pemerintah Tiongkok untuk menekan angka pertumbuhan penduduk adalah",
                    "membatasi jumlah anak yang boleh dimiliki",
                    "memberikan tunjangan bagi keluarga yang memiliki lebih dari tiga anak",
                    "membatasi jumlah anak yang boleh dimiliki", "melarang penduduk untuk menikah",
                    "meningkatkan kualitas untuk fasilitas kesehatan" },
            { 18, "Jepang mengimpor minyak bumi dari Indonesia sebagai bahan baku industrinya. Sementara, Indonesia mengimpor barang-barang industri Jepang, seperti motor, mobil, dan berbagai barang lainnya, untuk kebutuhan penduduknya. Hal ini merupakan contoh faktor pendukung interaksi keruangan yaitu",
                    "regional complementary", "intervening opportunity", "spatial transferability", "spatial pattern",
                    "regional complementary" },
            { 19, "Timbulnya suatu penemuan baru dalam masyarakat didorong kuat oleh faktor",
                    "adanya kesadaran masyarakat terhadap kurangnya unsur kebudayaan baru",
                    "rasa tidak puas terhadap hal yang sudah ada",
                    "keinginan untuk menyaingi bangsa lain yang sudah maju",
                    "adanya kesadaran masyarakat terhadap kurangnya unsur kebudayaan baru",
                    "adanya penghargaan penemuan baru" },
            { 20, "Dahulu, surat dikirim oleh petugas pos, saat ini sudah berkembang telepon, telepon seluler, e-mail, chat, dan video call. Pola hubungan sosial masyarakat secara perlahan berubah seiring perkembangan teknologi dan komunikasi. Berdasarkan laju kecepatannya, ilustrasi tersebut termasuk dalam bentuk perubahan",
                    "evolusi", "revolusi", "evolusi", "progress", "regress" },
            { 21, "Salah satu dampak negatif dari perubahan sosial budaya adalah masyarakat tidak siap menerima perubahan sosial sehingga meresponnya secara berlebihan ataupun menolak perubahan tersebut. Kondisi tersebut dikenal sebagai",
                    "cultural shock", "konflik sosial", "organisasi sosial", "cultural shock", "cultural lag" },
            { 22, "Modernisasi dan dan westernisasi merupakan hal yang berbeda, westernisasi merupakan sikap cenderung menyerap budaya atau gaya hidup barat dan tidak mengacu pada kemajuan, sedangkan modernisasi adalah",
                    "proses yang mengacu pada suatu kemajuan yang berasal dari manapun",
                    "proses yang mengacu pada kemajuan yang hanya berasal dari barat",
                    "situasi dimana masyarakat merasa belum siap dengan teknologi yang ada, sehingga adanya kecenderungan untuk menolak",
                    "keadaan dimana semua sistem masyarakat berubah tanpa adanya unsur budaya lama",
                    "proses yang mengacu pada suatu kemajuan yang berasal dari manapun" },
            { 23, "Modernisasi mencakup suatu transformasi total kehidupan bersama yang tradisional atau pra modern dalam arti teknologi serta organisasi sosial ke arah pola-pola ekonomi dan politis yang menjadi ciri-ciri negara yang stabil. Berikut ini yang menjadi syarat suatu wilayah telah mengalami proses modernisasi adalah",
                    "cara berpikir yang ilmiah", "cara berpikir yang ilmiah", "masyarakatnya bersifat tertutup",
                    "nilai-nilai tradisional masih kuat", "pola berpikir masyarakat bersifat tradisional" },
            { 24, "Globalisasi tentunya akan memberikan dampak di setiap bidang kehidupan. Di bawah ini yang merupakan contoh upaya dalam menghadapi globalisasi di bidang teknologi dan pendidikan adalah",
                    "pemakaian smartphone untuk menggali informasi dalam proses pembelajaran",
                    "pemakaian smartphone untuk menggali informasi dalam proses pembelajaran",
                    "menggunakan smartphone untuk mengakses resep masakan",
                    "mengakses internet hingga larut malam dan mengantuk di ruang kelas",
                    "pemanfaatan sosial media sebagai lahan bisnis online" },
            { 25, "Indonesia selalu membuka peluang kerjasama dengan negara lain dan organisasi internasional, misalnya dengan UNESCO yang bergerak di bidang ilmu pengetahuan, budaya, dan komunikasi. Kerjasama ini juga didukung oleh adanya kemajuan teknologi informasi, komunikasi dan transportasi di era globalisasi. Kerjasama ini menunjukkan adanya gejala globalisasi di bidang",
                    "politik", "politik", "hukum", "ekonomi", "transportasi" },
            { 26, "Salah satu dampak negatif dari perubahan sosial budaya adalah terjadinya perbedaan taraf kemajuan antara berbagai bagian dalam suatu kebudayaan karena ada yang tumbuh cepat dan ada yang tumbuhnya lambat. Kondisi tersebut dikenal sebagai",
                    "cultural lag", "konflik sosial", "organisasi sosial", "cultural shock", "cultural lag" },
            { 27, "Saat ini, tak jarang dijumpai remaja Indonesia mengikuti cara berpakaian ataupun perilaku selebriti dari berbagai belahan dunia. Hal ini dapat berdampak pada perilaku remaja seperti tidak mementingkan budaya lokal. Kasus tersebut menunjukkan bahwa dampak negatif globalisasi dalam kehidupan sosial budaya adalah",
                    "mudah terpengaruh budaya luar hingga cenderung melupakan budaya lokal",
                    "masuknya banyak tenaga kerja asing yang mendominasi tenaga kerja lokal",
                    "menumbuhkan sikap toleransi antarmasyarakat",
                    "mudah terpengaruh budaya luar hingga cenderung melupakan budaya lokal",
                    "memahami konsep multikulturalisme" },
            { 28, "Pusat Keuangan Amerika Serikat berada di", "New York", "New York", "Washington DC", "Chicago",
                    "Las Vegas" },
            { 29, "Berikut ini adalah negara yang dilalui oleh Pegunungan Alpen, kecuali", "Hungaria", "Austria",
                    "Liechtenstein", "Swiss", "Hungaria" },
            { 30, "Benua biru adalah sebutan bagi benua", "Eropa", "Asia", "Eropa", "Afrika", "Amerika" },
            { 31, "Ankara adalah ibukota dari negara", "Turki", "Libanon", "Bahrain", "Turki", "Qatar" },
            { 32, "Benua kuning adalah sebutan bagi benua", "Asia", "Asia", "Eropa", "Afrika", "Amerika" },
            { 33, "Suku Bugis berada di provinsi", "Sulawesi Selatan", "Sumatera Utara", "Sulawesi Selatan",
                    "Kalimantan Timur", "NTT" },
            { 34, "Tanggal 14 Agustus diperingata sebagai hari", "Pramuka", "Sumpah Pemuda", "Kesaktian Pancasila",
                    "Pramuka", "PMI" },
            { 35, "Taman hutan raya Ir. Juanda terletak di provinsi", "Jawa Barat", "Jawa Barat", "Jawa Tengah",
                    "Jawa Timur", "DKI Jakarta" },
            {36,"Vitamin yang banyak terkandung dalam buah-buahan adalah ?","Vitamin C","Vitamin A","Vitamin B","Vitamin C","Vitamin D"},
            {37,"Arah jam 9 itu sama dengan arah ?","Barat","Utara","Barat","Selatan","Timur"},
            {38,"Mata uang negara Jepang yaitu ?","Yen","Dollar","Peso","Euro","Dollar"},
            {39,"Layar komputer disebut juga","Monitor","Touchscrenn","TV","LED","Monitor"},
            {40,"Ibukota negara Rusia yaitu","Moscow","St. Petersburg","Kiev","Perm","Moscow"},
            {41,"Negara kecil yang sangat kaya dan benderanya sama dengan Belanda adalah","Luxemberg","Vatikan","Luxemberg","Yunani","Italy"},
            {42,"Pusat keuangan kota Amerika Serikat adalah","New York","New York","Vanchouver","Washington DC","California"},
            {43,"Anjing Pitbull berasal dari negara","Inggris","Irlandia","Inggris","Spanyol","Swedia"},
            {44,"Penemu radio berasal dari negara","Italy","Inggris","Italy","Amerika","German"},
            {45,"Primata paling cerdas adalah","Simpanse","Monyet","Simpanse","Gorilla","Kera"},
            {46,"Casablanka adalah contoh merek produk","Parfum","Pakaian","Parfum","Tas","Elektronik"},
            {47,"Tari kecak adalah tari yang berasal dari daerah","Bali","Jatim","Bali","Jogja","Jabar"},
            {47,"Indonesia dijajah Jepang selama","3,5 tahun","3,5 tahun","2,5 tahun","2 tahun","4 tahun"},
            {48,"Lagu Pai Mura Rame berasal dari daerah","NTT","NTB","NTT","Maluku","Papua"},
            {49,"Film horor Insidious rilis pada tahun","2011","2010","2011","2012","2013"},
            {50,"Kapten Pattimura lahir di ?","Ambon","Maluku","NTT","NTB","Ambon"}

    };

    public Object[][] soal() {
        return this.array;
    }
}
